### ISSUE TITLE
Aeon4 sleap model for BAA-1104048, 49 performs poorly

### ISSUE THREAD

**Issue by jkbhagatio** [SainsburyWellcomeCentre/aeon_experiments#466]
@lochhh got these stats on single-animal frames after training:

BAA-1104048 Accuracy: 0.542
BAA-1104049 Accuracy: 0.872
ID accuracy: 0.706
Total tracks: 165264
Tracks identified: 165254
Tracks correctly identified: 116660 

@lochhh also noted that the frames on aeon4 appear to be more blurry than aeon3 for the top cam. We may try adjusting the lens focus.

**Comment by jkbhagatio** [comment]
Closing this as done.

**Comment by lochhh** [comment]
retrained model with ~200 more frames with temporal discontinuities (i.e. frames in which the diff in Euclidean distance with the previous frame > 100px)

model path: `/ceph/aeon/aeon/data/processed/test-node1/4546247/2024-02-13T17-00-00/topdown-multianimal-id-133/`

single animal frames:
BAA-1104048 Accuracy: 0.965
BAA-1104049 Accuracy: 0.924
ID accuracy: 0.944
Total tracks: 213528
Tracks identified: 213528
Tracks correctly identified: 201653

**Comment by lochhh** [comment]
AEON3 social 0.2
BAA-1104045 Accuracy: 0.968
BAA-1104047 Accuracy: 0.845
ID accuracy: 0.905
Total tracks: 179343
Tracks identified: 179348
Tracks correctly identified: 162383 

model path: Z:\aeon\data\processed\test-node1\4310907\2024-01-12T19-00-00\topdown-multianimal-id"
