### ISSUE TITLE
Create workflow to visualize all cameras

### ISSUE THREAD

**Issue by jkbhagatio** [SainsburyWellcomeCentre/aeon_experiments#481]
As a camera view sanity check.

In future, something similar could be done for other devices (e.g. a workflow just to view patches, microphones, etc.)

**Comment by glopesdev** [comment]
@aspaNeuro @jkbhagatio @Dario55 Is this visualizer supposed to be running all the time? This will increase our camera memory bandwidth and compute pressure by 9x. Is there a reason for having all cameras open at all times?

I couldn't understand the discussion fully during the meeting, but here is my interpretation of it and counter-arguments:
- USB or GPIO cable disconnects: this can happen but will be immediately caught by the alert system so we don't need a permanent camera visualizer for this.
- unexpected bumping of cameras: the most likely cameras for this to happen are the side patch cameras which are already permanently displayed in the control panel. for the top cameras this would require a more deliberate intervention.
- if we do need all cameras constantly visible for other reasons not listed here, then we should add only the remaining cameras and avoid the ones which are already always visible, and in that case I would also like to see a 48h continuous recording test to make sure the system is stable before placing animals in. As it is we simply cannot know the effects of adding 9 more full-frame copies to the visualizer stack.

**Comment by glopesdev** [comment]
If this is for pre-experimental checks, then my suggestion is that we simply make a separate workflow just for this, adapted from the camera calibration workflow, which already displays all cameras.

**Comment by jkbhagatio** [comment]
> If this is for pre-experimental checks, then my suggestion is that we simply make a separate workflow just for this

Sure @glopesdev, for me fine to just do this, @aspaNeuro ?

**Comment by aspaNeuro** [comment]
This workflow is only to display the cameras or is there anything else you guys want to include? 
Also let me note that this workflow cannot run at the same time has the social workflow.
Will implement tomorrow morning whatever you guys decide.

**Comment by jkbhagatio** [comment]
Sure, I guess a workflow just to display and log all cameras is good.

**Comment by jkbhagatio** [comment]
Closing this as we're going with approach in #494
