### ISSUE TITLE
Bug in commit hash used in 'D:/Tests' dir for test experiments on aeon3 and aeon4

### ISSUE THREAD

**Issue by jkbhagatio** [SainsburyWellcomeCentre/aeon_experiments#491]
The hash for "test" experiments is the last 7 alphanumerics of the full hash, rather than the first 7. Bug in Aeon.Acquisition.GetDataPath.

**Comment by glopesdev** [comment]
Fixed via https://github.com/SainsburyWellcomeCentre/aeon_acquisition/pull/206
