### ISSUE TITLE
Double 0's still show up in BlockState data

### ISSUE THREAD

**Issue by jkbhagatio** [SainsburyWellcomeCentre/aeon_experiments#497]
e.g.

![image](https://github.com/SainsburyWellcomeCentre/aeon_experiments/assets/14895866/6a6e627f-cda8-41d3-9d27-3def56470d03)

**Comment by jkbhagatio** [comment]
Ah, another issue in doing block analysis is that sometimes the patch state stream updates before the block state stream on block transition. So another reason to wait for heartbeats to do the transition

**Comment by jkbhagatio** [comment]
@glopesdev Duplicated in aeon_mecha here: https://github.com/SainsburyWellcomeCentre/aeon_mecha/issues/358

**Comment by glopesdev** [comment]
Fix is being deployed but still needs testing, so reopening for a little longer.
