### ISSUE TITLE
Social0.2 exp workflow logic stopped working on aeon3 and aeon4 around 2024-02-02 00:00:00

### ISSUE THREAD

**Issue by jkbhagatio** [SainsburyWellcomeCentre/aeon_experiments#498]
After stopping the workflows on both machines, and thereafter restarting, the workflow launched, but the env logic was not working: block timeout was static, and encoder was not being read while patch wheels were being spun.

**Comment by glopesdev** [comment]
@aspaNeuro was mentioning that the workflow logic remained stuck even after restarting the workflow. @jkbhagatio I am assuming you deleted the temp files to resume experiments? Next time this happens can you please save those temp files in a zip file and attach them to this issue so we can hopefully have a way to reproduce this?

@aspaNeuro was also mentioning that a manual copy of data to CEPH was underway when the crash happened. In general we should not copy data manually to CEPH while experiments are running, but if we really need to I would recommend the following procedure:

1. Stop the experiment
2. Move the data folder from `Tests` to `ProjectAeon`
3. Restart the experiment and the robocopy task

Robocopy will then automatically copy these files as part of the scheduled task.

Finally re. hardware or CEPH issues, next time try to notice if the computer reboot is really required, or if just deleting the temp files and the above data copy steps are enough. Just trying to isolate if this is an issue exclusively with the task logic, or with hardware / network, or an interaction between both of these.

**Comment by jkbhagatio** [comment]
Here are .tmp files from latest crash.
[tmp_crash.zip](https://github.com/SainsburyWellcomeCentre/aeon_experiments/files/14166428/tmp_crash.zip)

**Comment by jkbhagatio** [comment]
From a second time

[tmp_crash2.zip](https://github.com/SainsburyWellcomeCentre/aeon_experiments/files/14166483/tmp_crash2.zip)

**Comment by jkbhagatio** [comment]
Seems likely that it was triggered by maintenance / environment config loading

**Comment by glopesdev** [comment]
During tests today we seem to have found a sequence to somewhat reliably reproduce the issue:
1. Delete all temp files (`ResetStateRecovery.cmd`)
2. Start the workflow
3. Start the cameras
4. Add a subject
5. Stop Maintenance
6. Reload Environment

Unfortunately the issue is not deterministic, so it must be a race condition. We did however determine that the issue was happening when reloading environment and not on stop maintenance.

**Comment by jkbhagatio** [comment]
Reopening this as @lorycalca noticed this issue again in recent phields test experiments in aeon4
