### ISSUE TITLE
SubjectState stream not being written out to at chunk end?

### ISSUE THREAD

**Issue by jkbhagatio** [SainsburyWellcomeCentre/aeon_experiments#503]
I think somehow SubjectState is not obeying the convention of being written out to at every chunk, instead it seems to be waiting for subsequent events. This means if you add a subject via the GUI, SubjectState won't be written out to until the removal of that subject from the GUI, which can be days/weeks later, which appears to be the behavior we're currently observing.

**Comment by glopesdev** [comment]
@jkbhagatio indeed it looks like the closing durations were not set in the log nodes for some reason. I have fixed it but we should add this to one of the checklists for pre-experiment validation.
