### ISSUE TITLE
D:/ProjectAeon directory gets deleted from Aeon3 occasionally

### ISSUE THREAD

**Issue by jkbhagatio** [SainsburyWellcomeCentre/aeon_experiments#513]
Not sure why this happens, maybe something to do with Robocopy when an epoch finishes.

**Comment by glopesdev** [comment]
@jkbhagatio yes, this is likely Robocopy. Does it create any problems with the workflow? I feel that it shouldn't be a problem.

**Comment by glopesdev** [comment]
Looks like the robocopy process crashes if the directory does not exist the first time, so this needs to be revisited.

**Comment by aspaNeuro** [comment]
Was testing this and yes robocopy deletes the folder if empty at the end, and it is supposed to do so
