### ISSUE TITLE
Social exp workflows crash on subject removal

### ISSUE THREAD

**Issue by jkbhagatio** [SainsburyWellcomeCentre/aeon_experiments#514]
On both aeon3 and aeon4 today we noticed that, when multiple subjects were in the GUI, and we removed one of them, the social workflow crashed.

**Comment by aspaNeuro** [comment]
![image](https://github.com/SainsburyWellcomeCentre/aeon_experiments/assets/74330450/343f6313-a074-48a8-98a0-95a463fa7051)

**Comment by jkbhagatio** [comment]
Closed with #551
