### ISSUE TITLE
Tentative plan for the Sprint to get Neuropixels data by April 16

### ISSUE THREAD

**Issue by Dario55** [SainsburyWellcomeCentre/aeon_experiments#518]
This is a tentative plan. 
 
**Monday 8th**:  
- [x] Both machine have been running a long test over the weekend. Before turning off the workflow, move the headstage to check 
       sync post-hoc
- [x] Get everything ready for Tuesday. Dario cannot be in due to train strike but, but he can be connected remotely. Here we would need Neurogears support for some of the tasks.
     - [x] Fix the length of the cable
     - [x] Close the gate with acrylic
     - [x]  Add the “nest” with bedding (I was thinking of a large Petri dish blue tagged to the floor with a lot of nesting 
             material - the  white light one - in it)
     - [x] Add small Petri dishes for water and food.       
     - [x] Fix the tracking mask
     - [x] Fix the patch
     - [x] Make sure feeder is working
     - [x] Test the workflows as if we would be starting the experiment: add remove subject, go to maintenance 
     - [x] remove probe box with the cable ties 
     - [x] Neurogears to Explain how to use workflow to Lory, Jai, Dario
     - [x] Discuss shifts for the day after (Lory, Dario, Jai)

**Tuesday 9th**
 - [x] Start the mouse with no probe as first thing in the morning (bluetagged head stage). It would be better to have someone from Neurogears available in case of technical problems. As discussed, it would be better to monitor overnight this dude, This will be taken care by Dario, Jai, Lory
- [x]  Neurogears to look at data integrity to make sure everything is sync correctly and data (in particular ephys data) are usable       

**Wednesday 10th**
- [x]  Leave the mouse for as long as possible

**Thursday 11th**
- [x]  remove the headstage currently on the mouse and replace it with the Onix one. So on the day of the experiment all that is needed is to connect the Onix cable to the headstage and quickcast it.
- [x]  Train the probe mouse in getting pellets

**Friday 12th**
- [x]  Train the probe mouse in getting pellets if needed
- [x] Make sure the arena is ready for monday

**Monday 15th**
- [x] First thing in the morning start the recording with the probe mouse. Neurogears available in case something goes wrong.

**Comment by NeuroThom** [comment]
Checklist for running experiments with Ephys on AEON2 added to README.md in social folder: ..\GitHub\SainsburyWellcome\Aeon\aeon_experiments\workflows\social\README.md
