### ISSUE TITLE
Troubleshooting onix commutator

### ISSUE THREAD

**Issue by Dario55** [SainsburyWellcomeCentre/aeon_experiments#519]
09/04/2024 New test done with a probe free mouse. The headstage was npx2.0. The cable got tangled after 7.5 hours, much shorter than previous test (21h) in which the commutator was also not working for a few hours and in which the test was interrupted for technical issues (BNO crashes), not for tangling.
Next steps in order of relevance/actuations:
- [x] It was unclear if the commutator was spinning in phase with the mouse or in antiphase (conflicting reports from different people). The correct way for this to spin is (from the experimenter point of view: which means mouse is looked from above and commutator from below): if mouse turns clockwise, commutator has to go anticlockwise. Verify if this is actually the case in the current setup. FOR THE 64ch THEY WERE IN ANTIPHASE
**Tested on 10/04/2024, on the workflow currently run by the desktop link and it is correct.** 
- [x] Jai reported that having a loop in the center of the cable may increase cable inertia to the point that torque is not transmitted uniformly along the cable. Check if this is the case and get a shorter cable? (the cable Filipe shipped us were indeed shorter I think, so worth finding them). HOWEVER, THIS WAS THE CASE FOR THE 64 CH HEADSTAGE TOO.
- [x] We can increase the sampling of the headstage signal and make it less temporally jittery. With the 64ch headstage that was the case, however the signal was sent at 10Hz to the commutator. Try to update the bonsai module for this to get a commutation that follows mouse motion more closely.
- [x] The above are quick things we can look at today, after which we need to decide what to do for the 25th presentation
- [x] Additionally, it has been point out that the IMU may work optimally only if held perfectly vertical. However, the IMU also have a gravitometer I believe, so it is worth checking what happen if the commutator is held more parallel to the ground and see if the quaternion implemented by onix takes care of it or not. In the onix paper they don’t mention any specific correction they do, but it I also true max recording there is 8h. If not it may be possible to do it ourself programmatically and project the rotation onto the horizontal plane. HOWEVER, THIS WAS THE CASE FOR THE 64 CH HEADSTAGE TOO.
- [x] Look into ways for automatically detect the building up of the torque and automatically untwist the commutator (THE HOPE IS THAT THIS WON’T BE NEEDED FOR A COUPLE OF DAYS LONG RECORDING; BUT LIKELY IS FOR LONGER ONES-SOLVING THE POINTS ABOVE MAY TELL US IF THIS IS THE CASE OR NOT). Two suggestion here-
     - [x] visually guided: paint a stripe on the cable and film it. As the torque accumulates, the spatial frequency should increase. One complication is that one wants the cable always in the same condition for filming, so some heuristics like consider frames only when the mouse is in the centre of the arena may be applicable. An alternative may be a camera that moves in phase with the commutator (mounted on the same rail)
     - [x] having a torque sensor inside the rotary joint

**Comment by aspaNeuro** [comment]
The headstage that we are using:
https://open-ephys.org/onix/oeps-7744

**Comment by NeuroThom** [comment]
# Angle flipping with pitch.

Important note to understanding: Yaw is not interpreted as a twist (which is correct). However, when the headstage is tilted forward (pitch), the commutator reacts as if this is a rotation in the vertical axis, and moreover there appears to be a singularity at the horizontal plane, meaning the angle can flip when the pitch crosses the horizon, causing the commutator to do a full half turn when it passes this plane

**Comment by glopesdev** [comment]
Fixed via #523
