### ISSUE TITLE
Determine behavior and metadata for dummy patches

### ISSUE THREAD

**Issue by glopesdev** [SainsburyWellcomeCentre/aeon_experiments#539]
For the next round of social experiments, we need to add dummy patches in the foraging environment.

A dummy patch behaves exactly like a normal patch, and uses the exact same reusable modules, but the BNC cable connecting expander commands to the motor controller is disconnected. Also there will be no GUI to the dummy patch, which means the reset function is not exposed and therefore the motor controller will not function.

It would be useful to have a way to distinguish patches which are broken by design (i.e. dummy) from patches broken by accident. One way to do this is by introducing a naming convention, e.g. `DummyPatch1`.

**Comment by jkbhagatio** [comment]
Closed via #549
