### ISSUE TITLE
Add visualizer for dummy patch activity

### ISSUE THREAD

**Issue by glopesdev** [SainsburyWellcomeCentre/aeon_experiments#540]
To allow monitoring of dummy patch sensor and threshold crossings, we need an extra visualizer window. We don't need to visualize beam break activity, history of threshold values, or statistics of the dummy patch, so the below "minor" modification to the current patch grid might be enough.

![image](https://github.com/SainsburyWellcomeCentre/aeon_experiments/assets/5315880/e200dcc0-7707-4fae-9bca-1629baf99b57)

Which of the visualizers gets merged with the `CameraSelector` depends on development time available:
- Easiest would be to merge the heatmap, since it is an image source and `StreamSelector` currently requires all inputs to be of the same type;
- Most flexible would be to implement a new `VisualizerSelector` node that can receive an arbitrary number of visualizer mappings and switch between which mappings are active.

**Comment by jkbhagatio** [comment]
Closed with #545
