### ISSUE TITLE
RFID firmware on some RFIDs needs to be updated

### ISSUE THREAD

**Issue by jkbhagatio** [SainsburyWellcomeCentre/aeon_experiments#562]
Some RFIDs are returning an incorrect value from the microchipped animal. The firmware on these needs to be updated.

On aeon4:  PatchDummy, GateWest, GateEast

On aeon3: PatchDummy

**Comment by jkbhagatio** [comment]
Actually, we realize there is a new firmware version for these rfids, 1.3, that all rfids should be updated to

**Comment by aspaNeuro** [comment]
All updated on AEON3 and AEON4
