### ISSUE TITLE
Subject data not always loaded from tmp files on exp workflow restart

### ISSUE THREAD

**Issue by jkbhagatio** [SainsburyWellcomeCentre/aeon_experiments#599]
Possible race condition when loading subject data after a crash - sometimes restarting the workflow successfully loads data from other tmp files, but not the saved active subjects

**Comment by glopesdev** [comment]
@jkbhagatio just to confirm, is this restricted to the active subjects list? Or have you ever noticed this with other parameters as well?

**Comment by glopesdev** [comment]
Also, is this related to https://github.com/SainsburyWellcomeCentre/aeon_experiments/issues/570?

**Comment by jkbhagatio** [comment]
Oh oops, yes this is essntially duplicate of #570, will close this and reply there
